### ISSUE TITLE
UI for user dashboard page

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/cb-connect#16]
After applying, a user should:
[X] get an email asking them to verify their submission
![image](https://user-images.githubusercontent.com/4512699/52162917-61881d80-268f-11e9-9579-1a77598b1876.png)
![image](https://user-images.githubusercontent.com/4512699/52162927-7795de00-268f-11e9-85fd-6180d9b795b0.png)

[ ] After they click to verify the account, they should be redirected to their profile page (right now it looks like the profile page should be `/home`, but users are actually redirected to a link that looks like `http://localhost:3000/enroll-account/G-qr9CR7NTLM4uhWemg-39oXMDnwIQ9OXPwCtMH--I` after they click to verify in the email.)
[  ] Logged-in users should see a link to "Dashboard" on the navbar
[  ] On Dashboard page, users should see:
- an option to submit another card
- An anonymous board of already-submitted cards
- hearts on each card to click on, indicating they want to be matched with that card
- A list of previous matches
- An area where where the new pending match is displayed. Here, they can click to accept (start a conversation with) or reject the match. 
- An option to expire a card they previously submitted
- An option to edit a card they previously submitted

**Comment by lpatmo** [comment]
TODO: Upload a balsamiq mockup of what this profile page should look like.

**Comment by lpatmo** [comment]
Currently on the user profile page:
![image](https://user-images.githubusercontent.com/4512699/52537799-68fa9700-2d1f-11e9-8455-b4061ff93966.png)

Add: 
- Your current submission(s)
- Your current match
- Your previous matches
- A board where you can favorite unmatched entries

**Comment by angelocordon** [comment]
Proposed mock up, open to feedback

![image](https://user-images.githubusercontent.com/3891869/53687563-fa3fa680-3cea-11e9-8fc2-61e2cdb9d3a8.png)
