### ISSUE TITLE
Devmode should be possible without a mailserver

### ISSUE THREAD

**Issue by sebbel** [codebuddies/cb-connect#36]
https://docs.meteor.com/api/email.html
Make MAIL_URL undefined and it will log the email to the logs.
Else you get an error :(

**Comment by distalx** [comment]
Hi @sebbel, 
What is the exact error are you getting? - I'm not able to reproduce this.

**Comment by sebbel** [comment]
I am unable to reproduce now. It might have been a problem with WSL :( sorry for the noise
