### ISSUE TITLE
[HTML/CSS] Consistent card UI on the board

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/cb-connect#38]
The UI on the cards in the board on the home page should match that of the cards on /dashboard. 

Before:
![image](https://user-images.githubusercontent.com/4512699/55353329-e2894880-5477-11e9-9d76-09e25fcbea12.png)

After:
![image](https://user-images.githubusercontent.com/4512699/55353360-f2a12800-5477-11e9-91e2-a18c8deae933.png)

**Comment by angelocordon** [comment]
Closing issue as #69 drops the need for the board component on the landing page.
