### ISSUE TITLE
[UI] Clarify the field requirements on the 2nd application step

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/cb-connect#4]
![image](https://user-images.githubusercontent.com/4512699/49860801-63301600-fdaf-11e8-97db-6ad1a1813f60.png)

We accept `pattern="[A-Za-z]{5,50}"` for the name and `pattern="[A-Za-z]{8,140}"` for the one-line intro, but it's not immediately obvious to the user right now that the name can't include numbers, for example. Or that it has to be between 5 and 50 characters.

TODO:
- Return an error warning about the requirement for each field

**Comment by stain88** [comment]
Is there a reason you don't want numbers for the name? can't it match the slack name?

**Comment by lpatmo** [comment]
Clarification, sorry: We _do_ want to allow numbers in general, and probably also underscores. So the pattern should expand.

**Comment by lpatmo** [comment]
Patterns should be fixed now.
