### ISSUE TITLE
[Feature] Add Continuous Integration Service

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/cb-connect#40]
Evaluate and implement a continuous integration service for open source projects ([Travis-CI](https://travis-ci.org), [CircleCi](https://circleci.com), or [CodeShip](https://codeship.com/)). Main priority is to be able to run our testing frameworks on PRs and report back into GitHub so that we can automatically see if PRs are mergeable without failing specs.

--
Secondary goal would be to automatically deploy main branches (`staging` or `master`) to our Digital Ocean droplets as soon as conditions are good, but I think this part might need a broader discussion.

**Comment by distalx** [comment]
Codeship.

**Comment by angelocordon** [comment]
I'd also like to look into how many concurrent builds we can run at a given time. Looks like Codeship and CircleCI is 1; I can't tell from the Travis website, but looks like they focus more on open source projects rather than enterprise level projects.
