### ISSUE TITLE
Redirect user to /dashboard after they click on the email link

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/cb-connect#50]
When a user clicks on the following link in their email, they should be redirected to /dashboard.

![image](https://user-images.githubusercontent.com/4512699/55673777-425d6600-5861-11e9-99a0-88b9ae6d50c6.png)

**Comment by distalx** [comment]
When a user clicks on that initial link they where taken to `/enroll-account/` page. 
On that page user sets their initial password.

If we redirect user to a `/dashboard` How user will set their password?

**Comment by lpatmo** [comment]
Sorry, I mean after they're taken to /enroll-account and set their password, they seem to redirect to a blank page instead of to /dashboard.
