### ISSUE TITLE
Define the minimal required node-version to run the app

### ISSUE THREAD

**Issue by code4cake** [codebuddies/cb-connect#58]
In the `package.json`  the `engines` specifies `node` as `8.11.4`, but this force us to run the application with only that specific version of node. This could be changed to 

```json
... rest_of_code
  "engines": {
    "node": ">= 8.11.4"  // => this is the minimum required node-version you need to have to run the application
  },
... rest_of_code
```

This can be enhanced by adding a `.node-version` or `.nvmrc` file - depends which node version manager we decide to go with  (`nvm` vs `nodenv`) -  to the root of the project, i.e:

```
# .node-version || .nvmrc
8.11.4
```
This will throw a warning if you try to run the application without having this version of node installed.

**Sidenote:** node is at `10.15.3` LTS at the moment, so we might want to upgrade.

**Comment by angelocordon** [comment]
Great feedback @dantesolis -- I don't know enough about Node to have a strong opinion on why we shouldn't do this (although, to your point, we're two major versions behind).

I _don't_ think managing versions of Node is a huge deal, so perhaps a `.node-version` file is fine or just defining `>=10.0.0` in our engine should work. To my understanding, I _believe_ Meteor contains the node and all of our dependencies for us.

 Feel free to put a PR 👍

**Comment by code4cake** [comment]
👍 @angelocordon sending a PR.
