### ISSUE TITLE
Add prop validations through prop-types to our React Components

### ISSUE THREAD

**Issue by angelocordon** [codebuddies/cb-connect#65]
Currently we have 31 warnings on missing prop validations. To follow modern best practices when composing React components, we should include prop types in our components (both for documentation purposes and type checking; will help us improve our tests). 

To see all components with missing prop types, run `meteor npx lint` in your terminal and it should return you a similar list of warnings:

![image](https://user-images.githubusercontent.com/3891869/56324502-deba1f00-6123-11e9-86c1-8ebc0fecc539.png)

The goal of this issue is to reduce the list down to `0`.

For reference, see:
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md
https://reactjs.org/docs/typechecking-with-proptypes.html
https://www.npmjs.com/package/prop-types

**Comment by lpatmo** [comment]
Word. Thanks for flagging! We should be using the `prop-types` library, right?

**Comment by angelocordon** [comment]
Yup! I believe as of React 15, it's now a separate library.

**Comment by Dan-Y-Ko** [comment]
why not just use typescript? :D

**Comment by angelocordon** [comment]
I thought about switching over to TSX, but I think that might add another barrier for entry to other contributors. I'd like to keep our prerequisites as low as possible.

We could potentially add Flow down the line as that can be a bit more optional, but for now this seems like the correct path to go on in our current state.

**Comment by angelocordon** [comment]
Assigned to @mcsmithers
